bs = float(input("Enter your Basic Salary :"))
eh = float(input("Enter the number Extra Hours worked :"))
wd = int(input("Enter number of working days :"))
pa = float(wd*(bs*(5/100)))
ot = float(eh*250)
gs = int(bs+pa+ot)
print(gs)
ns = float(gs-(gs*(12/100)))
print(ns)
